# action.yml
name: 'Kubernetes CLI'
description: 'Github action to manage k8s'
author: gabryel8818 <gabriel_melo88@hotmail.com>
branding:
  icon: terminal
  color: black
inputs:
  args:
    description: 'Kubectl Arguments'
    required: false
    default: 'version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
