on: [push]

jobs:
  kubectl:
    runs-on: ubuntu-latest
    name: teste
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: kubectl teste
        uses: ./ # Uses an action in the root directory
        id: kubectl
        env:
          BASE64_KUBE_CONFIG: "VEVTVEUK"
          KUBECTL_VERSION: '1.23.6'
